export const PLAN_PERMISSIONS = {
  Starter: [
    FEATURES.FOLLOW_UPS,
    FEATURES.REMINDERS,
    FEATURES.INCOMPLETE_RECOVERY,
  ],

  Pro: [
    FEATURES.FOLLOW_UPS,
    FEATURES.REMINDERS,
    FEATURES.INCOMPLETE_RECOVERY,
  ],

  Premium: [
    FEATURES.GROUP_AUTOMATION,
    FEATURES.FOLLOW_UPS,
    FEATURES.REMINDERS,
    FEATURES.INCOMPLETE_RECOVERY,
    FEATURES.ADVANCED_ANALYTICS,
    FEATURES.ADVANCED_INTEGRATIONS,
  ],
};