export const FEATURES = {
  GROUP_AUTOMATION: "GROUP_AUTOMATION",

  FOLLOW_UPS: "FOLLOW_UPS",

  REMINDERS: "REMINDERS",

  INCOMPLETE_RECOVERY: "INCOMPLETE_RECOVERY",

  ADVANCED_ANALYTICS: "ADVANCED_ANALYTICS",

  ADVANCED_INTEGRATIONS: "ADVANCED_INTEGRATIONS",
};

export const PLAN_PERMISSIONS = {
  Starter: [],

  Pro: [],

  Premium: [
    FEATURES.GROUP_AUTOMATION,

    FEATURES.FOLLOW_UPS,

    FEATURES.REMINDERS,

    FEATURES.INCOMPLETE_RECOVERY,

    FEATURES.ADVANCED_ANALYTICS,

    FEATURES.ADVANCED_INTEGRATIONS,
  ],
};

export function hasPermission(
  plan,
  feature
) {
  return (
    PLAN_PERMISSIONS[plan] || []
  ).includes(feature);
}